### ISSUE TITLE
GitLab Geo is not supported with this license.

### ISSUE THREAD

**Issue by Warvox** [CONIGUERO/gitlab-license#4]
### **Good time of day!**

Unfortunately, this type of license does not support the ability of Gitlab Geo to work. Issues the following errors on the secondary site...
```
GitLab Geo is not supported with this license. Please contact the sales team: https://about.gitlab.com/sales.
```
AND
```
remote:
remote: ========================================================================
remote:
remote: Your current license does not have GitLab Geo add-on enabled.
remote:
remote: ========================================================================
remote:
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Perhaps someone managed to make Geo work. If so, I will be glad to find out the correct activation method.

**Peace to all!**

**Comment by ssdrive-flaktra** [comment]
You have to set your plan to Ultimate.
```ruby
license.restrictions      = {
  plan: 'ultimate',
  # STARTER_PLAN = 'starter'
  # PREMIUM_PLAN = 'premium'
  # ULTIMATE_PLAN = 'ultimate'

  active_user_count: 2147483647,
  # required, just dont overflow
}
```

**Comment by Warvox** [comment]
Thank you for the answer, but unfortunately this method did not help me.
With an activated license (plan Ultimate), it does not allow you to clone or pull a project from the repository.
When cloning, it returns the following error:
```
remote: Your current license does not have GitLab Geo add-on enabled.
```
Tell me, please, on which version of gitlab do you have gitlab geo running with all the activated features?
